CREATE TABLE users
(
    id UUID PRIMARY KEY,
    first_name VARCHAR(55)  NOT NULL ,
    last_name VARCHAR(55) NOT NULL, 
    email VARCHAR(255) NOT NULL ,
    pass TEXT NOT NULL ,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE DEFAULT NULL
);